sudo: required
services:
  - docker

# Building all docker container based on 64 bit image
script:
  - make -j 3 caddy postgres monit
  - travis_wait 30 make architecture=amd64 src
  - travis_wait 30 make architecture=armhf src
  - travis_wait 30 make architecture=aarch64 src
  - docker images
