version: '2'

volumes:
  sqlitedb:
    driver: local

networks:
  backend:
    driver: bridge
  internal:
    driver: bridge

services:
  #Uncomment for using PSQL
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    networks:
      - internal
    environment:
      - POSTGRES_DB=pymonit

  monitcollector:
    build: ./src
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app
      - sqlitedb:/usr/src/app/data
    ports:
      - "8000:8000"
    #Uncomment for using PSQL
    depends_on:
      - db
    networks:
      - internal
      - backend
    environment:
      - DECOUPLE_DB=postgresql://postgres:postgres@db/pymonit

  monit:
    build: ./monit
    privileged: True
    network_mode: "host"
    volumes:
      - ./monit/basic:/etc/monit/monitrc.d/basic
